mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'polls.views.custom_error_pages.not_found_handler'
handler403 = 'polls.views.custom_error_pages.forbidden_handler'

polls/urls.py
from django.urls import path, re_path
from .views import \
    index,\
    greetings,\
    redirect_example,\
    current_datetime,\
    upload_file,\
    MyView,\
    MorningGreetingView,\
    ProtectedView,\
    StatementList,\
    StatementDetail,\
    MusicianCreate,\
    MusicianUpdate,\
    MusicianDelete,\
    MusicianDetail,\
    MusicianList
from django.contrib.auth.decorators import login_required, permission_required

app_name = 'polls'
urlpatterns = [
    path('', index.index_page, name='index'),
    path('<int:year>/greet', greetings.greet, name='greet'),
    path('redirect', redirect_example, name='redirect'),
    path('datetime', current_datetime, name='datetime'),
    path('upload', upload_file.upload_file, name='upload'),
    path('upload_for_model', upload_file.model_file_upload, name='model_upload'),

    #class based views
    path('my_view', MorningGreetingView.as_view(), name='my_view'),
    path('decorator', ProtectedView.as_view(), name='decorator'),
    path('statement_list', StatementList.as_view(), name='statement_list'),
    re_path('statement_detail/(?P<pk>\\d+)/$', StatementDetail.as_view(), name='statement_detail'),

    re_path('musician_detail,/(?P<pk>\\d+)/$', MusicianDetail.as_view(), name='musician_detail'),
    path('musician_create', MusicianCreate.as_view(), name='musician_create'),
    path('musician_update/<int:pk>/', MusicianUpdate.as_view(), name='musician_update'),
    path('musician_delete/<int:pk>/delete', MusicianDelete.as_view(), name='musician_delete'),
    path('musician_list', MusicianList.as_view(), name='musician_list'),
]

polls/models/musician.py
from django.db import models
from django.urls import reverse


class Musician(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()

    def get_absolute_url(self):
        return reverse('polls:musician_detail', kwargs={'pk':self.pk})

polls/models/statements.py
from django.db import models
from django.contrib.auth.models import User


class Statement(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    additional_data = models.CharField(max_length=200)
    file_path = models.CharField(max_length=200)
    file = models.FileField(upload_to='polls/images')

    class Meta:
        ordering = ['file']

    def __str__(self):
        return self.additional_data

polls/forms.py
from django import forms
from .models import Statement

class CalendarWidget(forms.TextInput):
    class Media:
        css = {
            'all': ('pretty.css',)
        }
        js = ('animations.js', 'actions.js')


class RegisterForm(forms.Form):
    name = forms.CharField(label='Your name ', max_length=100, initial='abeke')
    email = forms.EmailField(label='Your email ', max_length=200, initial='abekedevelops@gmail.com')
    password = forms.CharField(label='Your password ', max_length=100, initial=123)
    confirm_password = forms.CharField(label='Confirm Your password ', max_length=100, initial=123)
    # photo = forms.FileField()


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=100, initial='some title')
    file = forms.FileField()


class StatementForm(forms.ModelForm):
    class Meta:
        model = Statement
        fields = ['additional_data', 'file_path', 'file']

polls/views/datetime.py
from django.http import HttpResponse
import datetime


def current_datetime(request):
    now = datetime.datetime.now()
    formatted_date = now.strftime("%d-%m-%Y %H:%M:%S")
    html = "<html><body>It is now %s.</body></html>" % formatted_date
    return HttpResponse(html)

polls/views/greetings.py
from django.http import HttpResponse
from django.shortcuts import render


def greet(request, year):
    return HttpResponse("Hello %d" % year)

polls/views/index.py
from django.db import models

from django.http import HttpResponse


def index_page(request):
    return HttpResponse('index page')

polls/views/redirect.py
from django.http import HttpResponseRedirect
from django.urls import reverse


def redirect_example(request):
    year = 2021

    return HttpResponseRedirect(reverse('polls:greet', args=(year,)))

polls/views/upload_file.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from ..forms import UploadFileForm, StatementForm
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.contrib.auth.models import  User


def upload_file(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request, request.FILES['file'])
            return HttpResponseRedirect(reverse('polls:index'))
    else:
        form = UploadFileForm()
    return render(request, 'polls/upload_file.html', {'form': form})


def handle_uploaded_file(request, f):
    filename = request.POST['title']
    with open(filename + '.jpg', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


# @require_http_methods(['POST'])
def model_file_upload(request):
    if request.method == 'POST':
        form = StatementForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                user = User.objects.get(pk=5)
                statement = form.save(commit=False)
                statement.user = user
                statement.save()
            except Exception as e:
                messages.add_message(request, messages.ERROR, str(e))

        messages.add_message(request, messages.ERROR, 'File uploaded successfully')
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        form = StatementForm()
    return render(request, 'polls/statement_form.html', {'form': form,})

polls/templates/polls/authentication.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {{ form }}
</form>
</body>
</html>

polls/templates/polls/class_based/musician_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create musician</title>
</head>
<body>
    <h3>Create musician page</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create musician">
    </form>

    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
</body>
</html>

polls/templates/polls/class_based/musician_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Musician delete page</title>
</head>
<body>
    <h3>Are you sure to delete {{ musician.name }} ?</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Delete">
    </form>
</body>
</html>

polls/templates/polls/class_based/musician_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Musician detail</title>
</head>
<body>
    <h1>Musician detail page</h1>
    <p>Musician name: {{ musician.name }}</p>
    <p>Musician age: {{ musician.age }}</p>
</body>
</html>

polls/templates/polls/class_based/musician_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Musician list</title>
</head>
<body>
    <ul>
        {% for musician in musician_list %}
            <li>
                <a href="{% url 'polls:musician_update' pk=musician.id %}">
                    {{ musician.name }} Update
                </a>
                <a href="{% url 'polls:musician_delete' pk=musician.id %}">
                    {{ musician.name }} Delete
                </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/class_based/musician_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Musician update page</title>
</head>
<body>
    <h3>Update musician page</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update">
    </form>
</body>
</html>

polls/templates/polls/class_based/secret.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Secret page</title>
</head>
<body>
    <h1>This is a secret page</h1>
</body>
</html>

polls/templates/polls/class_based/statement_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statement detail page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/colors.css' %}">
</head>
<body>
    <h1>This is a statement detail page</h1>
    <p>Statement id is: {{ statement.id }}</p>
    <p>File data:</p><br>
    <p>File name: {{ statement.file }}</p>
    <p>File size: {{ statement.file.size }}</p>
    <img src="{% static 'polls/images/bg.jpg' %}" alt="This is an image">
    <img src="{{ statement.file }}" alt="This is an image">
</body>
</html>

polls/templates/polls/class_based/statement_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statement List</title>
</head>
<body>
    <a href="{% url 'polls:index' %}">Index page</a>
    {% block content %}
        <h2>Statements</h2>
        <ul>
            {%  for statement in stats %}
                <li>
                    <a href="{% url 'polls:statement_detail' pk=statement.id %}">
                        {{ statement.additional_data }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endblock %}
</body>
</html>

polls/templates/polls/custom_error_pages/403_custom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forbidden page</title>
</head>
<body>
    <h1>This is a forbidden page! Please log in!</h1>
</body>
</html>

polls/templates/polls/custom_error_pages/404_custom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page not found!</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
    <h1>Page you requested not found! Contact administrator</h1>
</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
        </label>
        <br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

{#<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">#}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/colors.css' %}">
<h1>Welcome to index page!</h1>
<ul>
    <li>
        <a href="{% url 'polls:model_upload' %}">
            Model upload page
        </a>
    </li>
    <li>
        <a href="{% url 'polls:statement_list' %}">
            Statement list
        </a>
    </li>
    <li>
        <a href="{% url 'polls:musician_create' %}">
            Create musician
        </a>
    </li>
        <li>
        <a href="{% url 'polls:musician_list' %}">
            Musician list
        </a>
    </li>
</ul>

{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

polls/templates/polls/register.html
<form action="{% url 'polls:registered' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="OK">
    {% if message %}
        <h1>ERRORRRRRR same email again???</h1>
    {% endif %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/statement_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statement Form</title>
</head>
<style>
    .header {
        text-align: center;
    }
    .form {
        display: flex;
    }
</style>
<body>
<h3 class="header">File upload form</h3>
<form class="form" action="{% url 'polls:model_upload' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form|linebreaksbr }}
    <input type="submit" value="Upload">
</form>
</body>
</html>

polls/templates/polls/upload_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File upload form</title>
</head>
<style>
    .header {
        text-align: center;
    }
    .form {
        display: flex;
    }
</style>
<body>
<h3 class="header">File upload form</h3>
<form class="form" action="{% url 'polls:upload' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form|linebreaksbr }}
    <input type="submit" value="Upload">
</form>
</body>
</html>